apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-cloudbuild-prod
  template:
    metadata:
      labels:
        app: hello-cloudbuild-prod
    spec:
      containers:
        - name: hello-cloudbuild-prod
          image: "us-east1-docker.pkg.dev/qwiklabs-gcp-04-b218c8b45888/my-repository/hello-cloudbuild-prod:v1.0"
          ports:
            - containerPort: 8080
